### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Tapppi** [stevemao/mock-bin#2]
This module wont work on windows due to the following issues:
1. windows searches the path for executables but if the exec doesn't have a file extension it searches for files with extensions from PATHEXT environment variable. Thus a mock file such as "git" is never found because when it is being searched Windows searches for "git.exe" "git.cmd" "git.bat" etc.
2. windows doesn't support shebangs so even if the command was magically found, it would not be executed as a node script.

The solution to both of these is to use ForbesLindesay/cmd-shim. It's the same package npm uses to create the executables in node_modules/.bin/ for windows. One caveat is that the actual mock bin will need a mock extension, because `cmd-shim` creates a cygwin startup script with the bin's name. About to open a pull request.

**Comment by stevemao** [comment]
What shell are you using? I use powershell and git-bash for work (I never use Windows for my open source projects though) and they do support shebangs.

**Comment by Tapppi** [comment]
Tried this with cmd.exe and cygwin bash. Neither worked, but cygwin doesn't work because [child_process.spawn still spawns the child process with cmd.exe](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options). It's the same with `shelljs.exec` and `childProcess.exec`

**Comment by Tapppi** [comment]
It's seems plausible that this could be also "fixed" by using `childProcess` `exec`/`spawn` with the `options.shell = /*powershell path*/` in packages using this, but that requires them to
1. find the powershell path
2. always specify it when using e.g. `childProceess.spawn` or `shelljs.exec`
instead of it "just working". Seems like an unnecessary amount of hassle.

**Comment by stevemao** [comment]
I don't think cmd.exe and cygwin are supported by nodejs/npm. You might always use git-bash or powershell.

**Comment by Tapppi** [comment]
Where did you get that idea? Of course they do, **`npm` uses** the `cmd-shim` package I used in that pull request. Child_process spawns **everything** with `cmd.exe` by default on windows.

**Comment by stevemao** [comment]
Ok, I'm no Windows expert. And I don't particularly like it :) If you could help setting up a Windows CI everything would be clear 😄

**Comment by Tapppi** [comment]
Sure, that was on my to do list anyway! I'll open up a PR shortly. I'm just stuck on supporting windows for work reasons, but still want to use the awesome OSS I use for personal projects too :blush:

**Comment by Tapppi** [comment]
Added the appveyor ci config to #3.
